CREATE TABLE IF NOT EXISTS WALLETS (
  ID INT NOT NULL UNIQUE,
  BALANCE INT NOT NULL,

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USERS (
  ID INT NOT NULL UNIQUE,
  NAME VARCHAR(255) NOT NULL,
  CPF VARCHAR(11) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  TYPE TEXT NOT NULL,
  WALLET_ID BIGINT NOT NULL,

  FOREIGN KEY (WALLET_ID) REFERENCES WALLETS(ID),

  PRIMARY KEY (ID)
);

INSERT INTO WALLETS (ID, BALANCE) VALUES
(1, 600),
(2, 500),
(3, 200);

INSERT INTO USERS (ID, NAME, CPF, EMAIL, PASSWORD, TYPE, WALLET_ID) VALUES
(1, 'Alice Silva', '12345678901', 'alice@example.com', 'password123', 'admin', 1),
(2, 'Bob Oliveira', '98765432109', 'bob@example.com', 'password456', 'user', 2),
(3, 'Carol Souza', '12312312312', 'carol@example.com', 'password789', 'user', 3);